name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: NodeJs set up üìÄ
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run Unit test on server app üìê
        working-directory: server
        env:
          CI: false
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: |
          set -x
          npm ci
          npm test

      - name: Build Client app ‚≠ê
        working-directory: client
        env:
          CI: false
          NODE_OPTIONS: '--max-old-space-size=8192'
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG }}
          REACT_APP_FPT_API_KEY: ${{ secrets.REACT_APP_FPT_API_KEY }}
          REACT_APP_FPT_API_ID: ${{ secrets.REACT_APP_FPT_API_ID }}
        run: |
          set -x
          npm ci
          npm run build

      - name: Archive build artifact ‚ÜóÔ∏è
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./client/build

      - name: Download artifact ‚ÜôÔ∏è 
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy release app to Firebase üöÄ
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MERN_ECOMMERCE_B848D }}'
          channelId: live
          projectId: mern-ecommerce-b848d
