#name: Build and Deploy to Github Pages
#on:
#  push:
#    branches:
#      - 'master'
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [14.x]
#
#    steps:
#      - name: Checkout ğŸ›ï¸
#        uses: actions/checkout@v2.3.1
#
#      - name: Cache node modules ğŸ§‘â€ğŸ”§
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: npm-${{ hashFiles('package-lock.json') }}
#          restore-keys: npm-
#
#      - name: Install dependencies ğŸ”§
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: cd ./client && npm ci --ignore-scripts
#
#      - name: Build ğŸ› ï¸
#        run: cd ./client && npm run build
#
#      - name: Deploy ğŸš€
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          branch: release # The branch the action should deploy to.
#          folder: client/build # The folder the action should deploy.
